# Generated by Django 3.2 on 2022-09-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_contactus_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
