# Generated by Django 3.2 on 2022-09-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220826_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_abv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
